# -*- coding: utf-8 -*-
"""feature engineering.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1St9eP6y2rFDNOBFVw7tUS2Ts1LJ26GKw
"""

# Feature Engineering - Combining Signal Strength and Speed
import os
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import joblib  # For saving the LabelEncoder

# Loading the preprocessed dataset
df = pd.read_csv('preprocessed_dataset.csv')

# Defining weights
w_signal = 0.5
w_speed = 0.5

# Calculating combined metric for each provider
df['gp_combined'] = w_signal * df['gp_strength'] + w_speed * df['gp_speed']
df['robi_combined'] = w_signal * df['robi_strength'] + w_speed * df['robi_speed']
df['bl_combined'] = w_signal * df['bl_strength'] + w_speed * df['bl_speed']

# Determine the best provider based on combined metrics
combined_metrics = df[['gp_combined', 'robi_combined', 'bl_combined']]
df['best_provider'] = combined_metrics.idxmax(axis=1).str.replace('_combined', '')

# Encoding 'best_provider'
label_encoder = LabelEncoder()
df['best_provider_encoded'] = label_encoder.fit_transform(df['best_provider'])

# Saving the LabelEncoder for future use
os.makedirs('best_models', exist_ok=True)
label_encoder_filename = 'best_models/label_encoder.pkl'
joblib.dump(label_encoder, label_encoder_filename)
print(f"Label encoder saved to '{label_encoder_filename}'.")

# Saving the dataset with combined features
df.to_csv('feature_engineered_dataset.csv', index=False)
print(f"Feature engineered dataset shape: {df.shape}")