# -*- coding: utf-8 -*-
"""plotting.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1St9eP6y2rFDNOBFVw7tUS2Ts1LJ26GKw
"""

# Data Visualization

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Loading the feature engineered dataset
df = pd.read_csv('feature_engineered_dataset.csv')

# Plotting the correlation heatmap
numerical_cols = df.select_dtypes(include=[np.number]).columns
plt.figure(figsize=(12, 8))
sns.heatmap(df[numerical_cols].corr(), annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

# Plotting distributions for key numerical features
key_features = ['temperature', 'longitude', 'latitude',
                'gp_combined', 'robi_combined', 'bl_combined']
for feature in key_features:
    plt.figure(figsize=(10, 6))
    sns.kdeplot(df[feature], shade=True, bw_adjust=1.5)
    plt.title(f'Distribution of {feature}')
    plt.xlabel(feature)
    plt.ylabel('Density')
    plt.show()